### ISSUE TITLE
[Suggestion] Compatible with OreDictionary version for 1.12.2

### ISSUE THREAD

**Issue by Robolightning** [Cadiboo/NoCubes#115]
Many mods are not supported by NoCubes, for this reason in the game on a large assembly you can often find not very beautiful joints.
I suggest:
1) Add support for the ore dictionary so that all types (stone, earth, foliage, ore) from all mods can be smoothed
2) Ability to configure blocks that should/should not be smoothed, preferably in list form

**Comment by Cadiboo** [comment]
Ore dictionary is not supported, but the mod is already entirely configurable.
There is a keybind for configuring the mod - look at the block you want to make smooth in-game and press the n key on your keyboard.
The config files for nocubes are stored in the server (world) config folder, the lists of what block should/should not be smoothed are in these config files.

**Comment by Robolightning** [comment]
> Ore dictionary is not supported, but the mod is already entirely configurable. There is a keybind for configuring the mod - look at the block you want to make smooth in-game and press the n key on your keyboard. The config files for nocubes are stored in the server (world) config folder, the lists of what block should/should not be smoothed are in these config files.
> 
> I’m not going to add ore dictionary compatibility because the existing system is already better than ore dictionary. Nocubes also provides a way for mod authors to automatically mark their blocks as smooth.

Why OreDict is not supported? Maybe is any alternative way to use it (for expample to check block drop item tables and get it from it, or check and make a list while game starts)?

**Comment by Robolightning** [comment]
> Ore dictionary is not supported, but the mod is already entirely configurable. There is a keybind for configuring the mod - look at the block you want to make smooth in-game and press the n key on your keyboard. The config files for nocubes are stored in the server (world) config folder, the lists of what block should/should not be smoothed are in these config files.
> 
> I’m not going to add ore dictionary compatibility because the existing system is already better than ore dictionary. Nocubes also provides a way for mod authors to automatically mark their blocks as smooth.

And maybe is ability to add block in ID list by hands as string (from game), and add the ability to write like "*ore*", where * is any string in id?

**Comment by Cadiboo** [comment]
> Why OreDict is not supported?

Because the current system of using BlockState strings instead of OreDictionary string is already better - every block has a corresponding BlockState string representation, but only some blocks have an OreDictionary string/name.
Also, OreDictionary doesn’t exist in 1.13+.
I’ll take a look at adding support for tags into the whitelist/blacklist system since I agree that wildcards would be a good idea, perhaps if this works it can be backported and in 1.12.2 would use ore dict.

> And maybe is ability to add block in ID list by hands as string (from game)

Yes, that’s already what you can do with the current system.  The strings are stored in your server (world) config file.  Pressing n while looking at a block instantly edits the config for you and adds the correct string, but you can still edit the config file yourself (and share it with others).
