### ISSUE TITLE
Crashes when running with better fooliage or optifine

### ISSUE THREAD

**Issue by 1JustVlad1** [Cadiboo/NoCubes#29]
With Better Fooliage: [crash-2019-04-14_21.27.26-client.txt](https://github.com/Cadiboo/NoCubes/files/3077613/crash-2019-04-14_21.27.26-client.txt)
With Optifine: [crash-2019-03-01_16.23.55-client.txt](https://github.com/Cadiboo/NoCubes/files/3077614/crash-2019-03-01_16.23.55-client.txt)

**Comment by Cadiboo** [comment]
> With BetterFoliage

I don’t see BetterFoliage mentioned anywhere in this, but your OptiFine version (OptiFine_1.12.2_HD_U_C6) is extremely outdated. NoCubes only supports HD_U_E2 and higher because OptiFine underwent significant internal changes from HD_U_D to HD_U_E.
> With OptiFine
This crash log is from a 1.13.2 Vanilla + OptiFine installation (1.13.2-OptiFine_HD_U_E4). NoCubes is not mentioned anywhere in this crash and would not have been loaded

**Comment by 1JustVlad1** [comment]
[crash-2019-04-14_21.59.04-client.txt](https://github.com/Cadiboo/NoCubes/files/3079448/crash-2019-04-14_21.59.04-client.txt)
Tried to do what you said, this crash report contains launch with betterFoliage and latest 1.12.2 Optifine version

**Comment by Cadiboo** [comment]
BetterFoliage requires [Forgelin](https://minecraft.curseforge.com/projects/shadowfacts-forgelin). It says this at the top of [the CurseForge project page] in red, but it’s pretty easy to miss.

**Comment by 1JustVlad1** [comment]
Oh, now I got it. My bad, thank you for helping me out
