### ISSUE TITLE
Does not render through portals (PortalGun Mod)

### ISSUE THREAD

**Issue by MorePortal** [Cadiboo/NoCubes#68]
![2019-12-04_18 21 30](https://user-images.githubusercontent.com/19516422/70155352-25648580-16c3-11ea-9a71-20f670fc7250.png)
Screenshot says everything

Mods:
	PortalGun-1.12.2-7.1.0.jar
	iChunUtil-1.12.2-7.2.2.jar
	NoCubes-1.12.2-0.4.0-pre1.jar

**Comment by Cadiboo** [comment]
Yeah I know. It has to do with how the portal gun mod works. The mod rebuilds all the chunks itself rather than using Minecrafts code. This means that the mod is incompatible with OptiFine’s shaders and NoCubes’ terrain changes. I’m planning on moving towards a dynamic baked model approach in my rewrite of the mod that will fix this. However, I also think that the portal gun mod should do its rendering with vanilla’s code rather than its own.

**Comment by Cadiboo** [comment]
Closed as soon 1.12.2 is unsupported by Forge and if I do backport to 1.12.2 it will be a full rewrite that will implicitly fix this issue.
